(load "interface.scm")
(load "generate.scm")
(load "books.scm")
(load "match-on.scm")
(load "reports.scm")
(load "regenerate.scm")
(load "mutate.scm")
(load "shuffle-assort.scm")



(define (trial-run)
  (for/and ([n one-run])
	(white-out!)
                    (match-on! A A-pay)
         (and population-channel (draw-population A))
	(and starting-strat-channel (draw-starting-strats A))
           (and fitness-channel (draw-fitness-pie A))
		(and demographic-channel (draw-demographic-pie A))
           (and payoff-series-channel (plot-series n))
           (and payoff-space-channel (plot-payoff-space A-pay))
           (abridged-report!)
           (sleep pause)
           (regenerate! A A-fit)
	(mutate! A)
	(fix! A)
	(shuffle! A)
	(assort! A)
	))

